"""
MediVision – LanguageManager
Supports English and Amharic (አማርኛ).
"""

TRANSLATIONS = {
    "en": {
        # General
        "app_name": "MediVision",
        "logout": "Logout",
        "settings": "Settings",
        "save": "Save",
        "cancel": "Cancel",
        "delete": "Delete",
        "edit": "Edit",
        "add": "Add",
        "view": "View",
        "search": "Search...",
        "loading": "Loading...",
        "back": "Back",
        "close": "Close",
        "submit": "Submit",
        "upload": "Upload",
        "download": "Download",
        "refresh": "Refresh",
        "yes": "Yes",
        "no": "No",
        "confirm": "Confirm",
        "status": "Status",
        "date": "Date",
        "actions": "Actions",
        "name": "Name",
        "role": "Role",
        "email": "Email",
        "username": "Username",
        "id": "ID",
        "age": "Age",
        "sex": "Sex",
        "male": "Male",
        "female": "Female",
        "online": "Online",
        "offline": "Offline Mode",

        # Dashboards
        "dashboard": "Dashboard",
        "welcome": "Welcome,",
        "today_cases": "Cases Today",
        "high_risk": "High Risk",
        "medium_risk": "Medium Risk",
        "low_risk": "Low Risk",
        "pending": "Pending Review",

        # Clinician
        "clinician_title": "Clinician Dashboard",
        "patient_list": "Patient List",
        "patient_id": "Patient ID",
        "risk_score": "TB Risk Score",
        "ai_result": "AI Analysis Result",
        "heatmap": "Grad-CAM Heatmap",
        "cxr_image": "Chest X-Ray",
        "threshold": "Sensitivity Threshold",
        "triage": "Triage Recommendation",
        "triage_high": "HIGH RISK — Prioritize GeneXpert confirmation and isolation.",
        "triage_medium": "MEDIUM RISK — Schedule sputum culture within 48h.",
        "triage_low": "LOW RISK — Routine follow-up recommended.",
        "approve_ai": "✔ Approve AI Result",
        "reject_ai": "✘ Reject AI Result",
        "generate_report": "Generate Report",
        "feature_importance": "Feature Importance (SHAP)",
        "risk_level": "Risk Level",
        "tb_score": "TB Abnormality Score",
        "clinical_data": "Clinical Data",
        "lab_data": "Laboratory Data",
        "hiv_status": "HIV Status",
        "hiv_pos": "HIV Positive",
        "hiv_neg": "HIV Negative",
        "symptoms": "Symptoms",
        "cough_2wks": "Cough >2 weeks",
        "fever": "Fever",
        "weight_loss": "Weight Loss",
        "night_sweats": "Night Sweats",
        "genexpert": "GeneXpert",
        "sputum": "Sputum Grading",
        "rifampicin": "Rifampicin Resistance",
        "run_analysis": "Run Analysis",
        "clinical_recommendation": "Clinical Recommendation",
        "no_patient": "Select a patient from the list",
        "cases_today": "Cases Today",
        "out_of_100": "out of 100",

        # Radiographer
        "radiographer_title": "Radiographer Dashboard",
        "upload_xray": "Upload Chest X-Ray",
        "drag_drop": "Drag & drop or click to upload",
        "supported_fmt": "Supported: JPG, PNG, DCM",
        "patient_meta": "Patient Metadata",
        "view_type": "View Type",
        "study_date": "Study Date",
        "send_analysis": "Send for AI Analysis",
        "upload_history": "Upload History",
        "preview": "Image Preview",
        "processing": "Processing...",
        "preprocessing": "Preprocessing",
        "upload_success": "Upload Successful",
        "new_case": "New Case",
        "my_cases": "My Cases",

        # Lab Technician
        "lab_title": "Lab Technician Dashboard",
        "lab_records": "Lab Records",
        "enter_lab_data": "Enter Lab Result",
        "link_patient": "Link to Patient ID",
        "upload_report": "Upload Lab Report",
        "genexpert_result": "GeneXpert Result",
        "sputum_grade": "Sputum Grade",
        "rifampicin_res": "Rifampicin Resistance",
        "save_sync": "Save & Sync",
        "detected": "Detected",
        "not_detected": "Not Detected",
        "positive": "Positive",
        "negative": "Negative",
        "grade_1": "Grade 1+",
        "grade_2": "Grade 2+",
        "grade_3": "Grade 3+",
        "scanty": "Scanty",
        "test_type": "Test Type",
        "result": "Result",
        "linked_patient": "Linked Patient",
        "recorded_by": "Recorded By",

        # Admin
        "admin_title": "System Administrator",
        "user_mgmt": "User Management",
        "system_logs": "System Logs",
        "data_sync": "Data Sync",
        "backup_restore": "Backup & Restore",
        "configuration": "Configuration",
        "add_user": "Add User",
        "remove_user": "Remove User",
        "assign_role": "Assign Role",
        "last_active": "Last Active",
        "log_event": "Event",
        "log_user": "User",
        "log_time": "Time",
        "sync_status": "Sync Status",
        "last_sync": "Last Sync",
        "sync_now": "Sync Now",
        "backup_now": "Backup Now",
        "restore": "Restore",
        "total_users": "Total Users",
        "active_sessions": "Active Sessions",
        "db_size": "Database Size",
        "uptime": "System Uptime",
        "config_language": "Default Language",
        "config_theme": "Default Theme",
        "config_timeout": "Session Timeout (min)",
        "config_save": "Save Configuration",
    },

    "am": {
        # General
        "app_name": "ሜዲቪዥን",
        "logout": "ወጣ",
        "settings": "ቅንብሮች",
        "save": "አስቀምጥ",
        "cancel": "ሰርዝ",
        "delete": "ሰርዝ",
        "edit": "አርትዕ",
        "add": "ጨምር",
        "view": "ዕይታ",
        "search": "ፈልግ...",
        "loading": "በሂደት ላይ...",
        "back": "ተመለስ",
        "close": "ዝጋ",
        "submit": "አስገባ",
        "upload": "ጫን",
        "download": "አውርድ",
        "refresh": "አድስ",
        "yes": "አዎ",
        "no": "አይ",
        "confirm": "አረጋግጥ",
        "status": "ሁኔታ",
        "date": "ቀን",
        "actions": "ድርጊቶች",
        "name": "ስም",
        "role": "ሚና",
        "email": "ኢሜል",
        "username": "የተጠቃሚ ስም",
        "id": "መታወቂያ",
        "age": "ዕድሜ",
        "sex": "ጾታ",
        "male": "ወንድ",
        "female": "ሴት",
        "online": "በመስመር ላይ",
        "offline": "ከመስመር ውጭ",

        # Dashboards
        "dashboard": "ዳሽቦርድ",
        "welcome": "እንኳን መጡ,",
        "today_cases": "የዛሬ ጉዳዮች",
        "high_risk": "ከፍተኛ ስጋት",
        "medium_risk": "መካከለኛ ስጋት",
        "low_risk": "ዝቅተኛ ስጋት",
        "pending": "ግምገማ ይጠብቃል",

        # Clinician
        "clinician_title": "የሀኪም ዳሽቦርድ",
        "patient_list": "የታካሚ ዝርዝር",
        "patient_id": "የታካሚ መታወቂያ",
        "risk_score": "የቲቢ አደጋ ነጥብ",
        "ai_result": "የ AI ትንታኔ ውጤት",
        "heatmap": "የሙቀት ካርታ",
        "cxr_image": "የደረት ኤክስ-ሬ",
        "threshold": "የስሜት ደረቃ",
        "triage": "የምርመራ ምክር",
        "triage_high": "ከፍተኛ ስጋት — GeneXpert ያስቸኩሉ።",
        "triage_medium": "መካከለኛ ስጋት — የጀርም ምርመራ ያቅዱ።",
        "triage_low": "ዝቅተኛ ስጋት — መደበኛ ክትትል ይደረግ።",
        "approve_ai": "✔ AI ተቀበሉ",
        "reject_ai": "✘ AI ውድቅ ያድርጉ",
        "generate_report": "ሪፖርት ፍጠር",
        "feature_importance": "የባህሪ አስፈላጊነት (SHAP)",
        "risk_level": "የአደጋ ደረጃ",
        "tb_score": "የቲቢ ነጥብ",
        "clinical_data": "ክሊኒካዊ ውሂብ",
        "lab_data": "የላብ ውሂብ",
        "hiv_status": "የኤችአይቪ ሁኔታ",
        "hiv_pos": "ኤችአይቪ ፖዘቲቭ",
        "hiv_neg": "ኤችአይቪ ኔጋቲቭ",
        "symptoms": "ምልክቶች",
        "cough_2wks": "ሳል >2 ሳምንት",
        "fever": "ትኩሳት",
        "weight_loss": "ክብደት መቀነስ",
        "night_sweats": "ምሽት ላብ",
        "genexpert": "ጂን ኤክስፐርት",
        "sputum": "የስፒዩተም ምርመራ",
        "rifampicin": "ሪፋምፒሲን መቋቋም",
        "run_analysis": "ትንታኔ አሂድ",
        "clinical_recommendation": "ክሊኒካዊ ምክር",
        "no_patient": "ታካሚ ከዝርዝሩ ይምረጡ",
        "cases_today": "የዛሬ ጉዳዮች",
        "out_of_100": "ከ 100",

        # Radiographer
        "radiographer_title": "የራዲዮግራፈር ዳሽቦርድ",
        "upload_xray": "የደረት ኤክስ-ሬ ጫን",
        "drag_drop": "ጎትቶ ጣል ወይም ጠቅ ያድርጉ",
        "supported_fmt": "ዓይነቶች: JPG, PNG, DCM",
        "patient_meta": "የታካሚ መረጃ",
        "view_type": "የእይታ ዓይነት",
        "study_date": "የጥናት ቀን",
        "send_analysis": "ለ AI ትንታኔ ላክ",
        "upload_history": "የጫን ታሪክ",
        "preview": "የምስል ቅድመ-ዕይታ",
        "processing": "በሂደት ላይ...",
        "preprocessing": "ቅድመ-ሂደት",
        "upload_success": "ስኬታማ ጫን",
        "new_case": "አዲስ ጉዳይ",
        "my_cases": "ጉዳዮቼ",

        # Lab Technician
        "lab_title": "የላብ ቴክኒሻን ዳሽቦርድ",
        "lab_records": "የላብ መዝገቦች",
        "enter_lab_data": "የላብ ውጤት ያስገቡ",
        "link_patient": "ከታካሚ መታወቂያ ጋር አስተሳሰር",
        "upload_report": "ሪፖርት ጫን",
        "genexpert_result": "GeneXpert ውጤት",
        "sputum_grade": "Sputum ደረጃ",
        "rifampicin_res": "ሪፋምፒሲን መቋቋም",
        "save_sync": "አስቀምጥ እና አመሳስል",
        "detected": "ተገኝቷል",
        "not_detected": "አልተገኘም",
        "positive": "ፖዘቲቭ",
        "negative": "ኔጋቲቭ",
        "grade_1": "ደረጃ 1+",
        "grade_2": "ደረጃ 2+",
        "grade_3": "ደረጃ 3+",
        "scanty": "ጥቂት",
        "test_type": "የምርመራ ዓይነት",
        "result": "ውጤት",
        "linked_patient": "ከታካሚ ጋር ተያይዟል",
        "recorded_by": "የተዘጋጀው በ",

        # Admin
        "admin_title": "የስርዓት አስተዳዳሪ",
        "user_mgmt": "የተጠቃሚ አስተዳደር",
        "system_logs": "የስርዓት ምዝግብ ማስታወሻ",
        "data_sync": "ውሂብ አመሳስሎ",
        "backup_restore": "ምትኬ እና ወደ ነበረበት መልስ",
        "configuration": "ቅንጅት",
        "add_user": "ተጠቃሚ ጨምር",
        "remove_user": "ተጠቃሚ አስወግድ",
        "assign_role": "ሚና ሰጥ",
        "last_active": "የመጨረሻ ንቁ ሁኔታ",
        "log_event": "ክስተት",
        "log_user": "ተጠቃሚ",
        "log_time": "ጊዜ",
        "sync_status": "የአመሳስሎ ሁኔታ",
        "last_sync": "የመጨረሻ አመሳስሎ",
        "sync_now": "አሁን አመሳስል",
        "backup_now": "ምትኬ ፍጠር",
        "restore": "ወደ ነበረበት መልስ",
        "total_users": "ጠቅላላ ተጠቃሚዎች",
        "active_sessions": "ንቁ ክፍለ ጊዜዎች",
        "db_size": "የውሂብ ጎታ መጠን",
        "uptime": "የስርዓት አሄድ ጊዜ",
        "config_language": "ነባሪ ቋንቋ",
        "config_theme": "ነባሪ ገጽታ",
        "config_timeout": "የክፍለ ጊዜ ማብቂያ (ደቂቃ)",
        "config_save": "ቅንጅት አስቀምጥ",
    }
}


class LanguageManager:
    def __init__(self):
        self.lang = "en"

    def get(self, key):
        return TRANSLATIONS.get(self.lang, {}).get(key, TRANSLATIONS["en"].get(key, key))

    def set_language(self, lang):
        if lang in TRANSLATIONS:
            self.lang = lang
