# Generated by Django 6.0.2 on 2026-02-23 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'Clinician'), ('R', 'Radiologist'), ('L', 'Administrator_Local'), ('A', 'Auditor'), ('P', 'Patient')], default='C', max_length=1),
        ),
        migrations.CreateModel(
            name='CXRImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cxr_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cxr_images', to='api.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='cxr_image',
            field=models.ManyToManyField(blank=True, related_name='patients', to='api.cxrimage'),
        ),
    ]
