# Generated by Django 6.0.2 on 2026-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role_cxrimage_patient_cxr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cxr_image',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'Clinician'), ('R', 'Radiologist'), ('L', 'Administrator_Local'), ('A', 'Auditor')], default='C', max_length=1),
        ),
        migrations.DeleteModel(
            name='CXRImage',
        ),
    ]
